#!/bin/bash

# Assignment from scripts arguments.
array=("$@")

array=(1 2 3 [3]=4)

echo "${array[@]}"
echo "${array[*]}"
echo "${array[@]:1:3}"
echo "${array[-1]}"

# Append
array+=('fourth' 'fifth')
echo "${array[@]}"
array=("${array[@]}" 'fourth' 'fifth')
echo "${array[@]}"

# Insert
arr=('a' 'b' 'c' 'd')
i=2
arr=("${arr[@]:0:$i}" 'new' "${arr[@]:$i}")
echo "${arr[@]}"

# Associative Arrays
declare -A aa
aa[deep]=kasodariya
aa[parth]=london

echo ${aa[deep]}
echo "${!aa[@]}"
echo "${aa[@]}"

# To unset the arrays memory.
unset aa

# Reading file into array.
readarray -t arr < file.txt
echo "${arr[@]}"
