#!/bin/bash

greet(){
	local name="$1"
	local val=${2: 20} # Default Args.
	echo "Hello, $name, $val"
}

greet "John Doe"
greet "John Doe" 10

foo(){
	local val=${1:?Must provide an argument}
	echo "$val"
}

foo
